### PR TITLE
Prevents players from breaking playerheads to bypass persistentheads using water.

### PR DESCRIPTION
**Pull request by JoelGodOfwar**

### CODE REVIEW

**Review by Prof-Bloodstone — COMMENTED** [review]
I'm not sure this is the best place to put it, tbh. I'd imagine some people might want to just persist name/role, but not make heads immune to water.

I think the name of the module might be a bit confusing because of what it does. I'd either extract it to separate module (what about "WaterProofHeads"?) or add settings for the 2 behaviors of this module. I'm leaning towards the first approach though.

@Machine-Maker what do you think about this?

**Comment by Machine-Maker** [comment]
Yeah, I don't think preventing heads from being broken by flowing water is the right solution, since that's a game mechanic in and of itself.

**Comment by Prof-Bloodstone** [comment]
Sorry, I misunderstood the purpose of this PR. Didn't think that water would not cause the BlockDropItemEvent to get called.

I can confirm this is an issue that should be fixed. But I'd rather do it keeping current behavior of them breaking.

**Comment by JoelGodOfwar** [comment]
It's a work around the lack of a break naturally event not existing. Maybe I should have created an issue ticket instead of a PR, but this code keeps the Persistent Heads from losing their names because of water breaking them.

**Comment by JoelGodOfwar** [comment]
I found a more vanilla fix, it retains the name, but not the lore.

**Pull request closed without merging**
