### PR TITLE
Head naming and lazy loading

### PR DESCRIPTION
**Pull request by NathanCollaert**
- Changed the naming convention of mob heads to be more inline with what Vanilla Tweaks does (\<Entity\>'s Head)[not bold].
- Lazy loading the creation of the TrackRawStats objectives, previously they were created even if the module wasn't enabled. Now they are created when the module is actually enabled.
- Edited the POM so the jar will have the version added to it (easier for server operators).

### CODE REVIEW

**Comment by Machine-Maker** [comment]
Remove the `*` import and should be good. Don't really like using the wildcard imports.

**Comment by NathanCollaert** [comment]
With all respect, why would a wildcard import for entities be negative for that class exactly? The class requires all entities, every version, because it adds a mob head drop to every entity. Instead of having to write 31+ imports you only have to write one.

**Comment by Machine-Maker** [comment]
You're right, all the interfaces in that package do have to be imported, I just think it should just be consistent across the project. Hardly anyone ever "writes" import statements manually nowadays anyways, and IDEs auto shrink the block so it doesn't take up a bunch of lines.

**Comment by NathanCollaert** [comment]
This would be it for this branch.

**Comment by NathanCollaert** [comment]
Removed the 1.17 heads from the branch above ^

**Pull request merged**
